import Header from "@/components/head";
import "./globals.css";

export const metadata = {
  title: "NEXT 앱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
